name: Build

on:
  push:
    branches:
      - "release/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Determining which lab should be released
        run: echo cat .build
             | echo "LAB_TITLE=$(cat .build)" >> $GITHUB_ENV
             | echo "RELEASE_TAG=$(echo "release/lab5" | awk '{n=split($1,A,"/"); print A[n]}')" >> $GITHUB_ENV
      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v2
        with:
          root_file: "*.tex"
          working_directory: "/github/workspace/src/${{ env.LAB_TITLE }}"
          glob_root_file: true
          latexmk_use_lualatex: true
          extra_fonts: "/github/workspace/src/static/roman.ttf"
      - name: Create a release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: "./src/${{ env.LAB_TITLE }}/*.pdf"
          automatic_release_tag: "${{ env.RELEASE_TAG }}"