name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX documents
        uses: xu-cheng/latex-action@v2
        with:
          root_file: src/labs/lab5.tex
          glob_root_file: true
          latexmk_use_lualatex: true
          extra_fonts: |
            ./src/static/Times New Roman.ttf
#          working_directory: "./src/labs"
      - name: Create a release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: "*.pdf"
          automatic_release_tag: "latest"